### ISSUE TITLE
Output of evaluation script with 0 values for Raw setting

### ISSUE THREAD

**Issue by matthias-samwald** [baharefatemi/SimplE#3]
I just ran the FB15K example and got this:

```
Loss in iteration 1000: 160424.18872070312(FB15K)
Saving the model
~~~~ Select best epoch on validation set ~~~~
50
Raw setting:
        Hit@1 = 0.0
        Hit@3 = 0.0
        Hit@10 = 0.0
        MR = 0.0
        MRR = 0.0

Fil setting:
        Hit@1 = 0.51695
        Hit@3 = 0.70038
        Hit@10 = 0.81951
        MR = 106.17348
        MRR = 0.6264143401644883

```

All the results for Raw setting are 0.

**Comment by baharefatemi** [comment]
Hi, I'm so sorry for my late reply. 
The code is written as you get raw and fil results on test otherwise only fil results.
You can change this line of code in test.py to get raw results for validation:
settings = ["raw", "fil"] if self.valid_or_test == "test" else ["fil"]
-> settings = ["raw", "fil"]
